In [1]:
import pandas as pd
import re

## Load Sequence Data 
To Determine Primers

In [2]:
sequences_df = pd.read_csv('sequences_all.tsv', delimiter='\t')
sequence_order_primer_type_df  = sequences_df.melt(id_vars= sequences_df.columns[0]) 
def funct_or_emo(string):
    if '-emo'in string:
        return 'emotional'
    if '-funct' in string:
        return 'functional'
    if '__' in string:
        return 'crosshair'
    return 'image'

def get_primed_image(string):
    if 'primer'in string:
        return re.search(r"-(?:emo|funct)-(.+)", string).group(1)
    return '_'.join(string.split('_')[1:])
sequence_order_primer_type_df['primer-type'] =  sequence_order_primer_type_df.value.apply(funct_or_emo)
sequence_order_primer_type_df['primed-image'] =  sequence_order_primer_type_df.value.apply(get_primed_image)
sequence_order_primer_type_df

,Sequence name/ Order,variable,value,primer-type,primed-image
0,A,0,0_primer-funct-4_floor-cleaner-4,functional,4_floor-cleaner-4
1,B,0,0_primer-emo-4_floor-cleaner-4,emotional,4_floor-cleaner-4
2,C,0,123_primer-emo-2_car-inside-3,emotional,2_car-inside-3
3,D,0,123_primer-funct-2_car-inside-3,functional,2_car-inside-3
4,E,0,0_primer-funct-4_floor-cleaner-4,functional,4_floor-cleaner-4
...,...,...,...,...,...
1723,H,143,125_2_car-inside-3,image,2_car-inside-3
1724,I,143,20_1_kitchen,image,1_kitchen
1725,J,143,20_1_kitchen,image,1_kitchen
1726,K,143,23_4_floor-cleaner-1,image,4_floor-cleaner-1
1727,L,143,23_4_floor-cleaner-1,image,4_floor-cleaner-1

In [3]:
sequences_df.columns[0]

'Sequence name/ Order'

In [4]:
survey_df = pd.read_csv('Experiment check list - survey responses.tsv', delimiter='\t')
survey_df.head()

,Timestamp,Please write your Subject ID number,What is your gender?,What is your age?,Are you wearing glasses or contact lenses?,What is your first language?,Are you currently enrolled in a Cognitive Science course?,image 1 - face,image 2 - face,image 3 - face,image 4 - face,image 5 - face,image 6 - face,image 7 - face,image 8 - face,image 9 - face,image 10 - face
0,11/13/2019 20:33:49,P001,Female,26,NaN,NaN,NaN,5,4,4,5,3,2,3,4,4,3
1,11/15/2019 9:18:27,P002,Female,24,I am wearing neither.,Danish,Yes,5,4,4,2,1,5,3,1,1,4
2,11/15/2019 10:00:40,P003,Female,24,I am wearing neither.,Danish,No,5,5,5,5,5,5,3,5,5,3
3,11/15/2019 12:14:16,P004,Female,26,I am wearing neither.,Danish,No,5,5,5,5,4,5,5,5,4,5
4,11/15/2019 12:18:23,P005,Female,24,I am wearing neither.,Lithuanian,Yes,4,4,3,2,3,1,3,2,2,1

## Survey Data
#### Get stats for image ratings

In [5]:
image_cols = [col for col in survey_df.columns if 'image' in col]
image_ratings_df = pd.DataFrame(survey_df[image_cols].mean()).rename(columns={0:'mean'})
image_ratings_df['median'] = survey_df[image_cols].median()
image_ratings_df['stdev'] = survey_df[image_cols].std()
image_ratings_df

                     mean  median     stdev
image 1 - face   4.833333     5.0  0.379049
image 2 - face   4.733333     5.0  0.520830
image 3 - face   4.200000     4.5  0.961321
image 4 - face   4.166667     4.5  1.053183
image 5 - face   3.500000     3.5  1.224745
image 6 - face   3.366667     3.0  1.425950
image 7 - face   3.166667     3.0  1.147211
image 8 - face   3.033333     3.0  1.245221
image 9 - face   3.066667     3.0  1.201532
image 10 - face  2.833333     3.0  1.341212

In [6]:
image_ratings_df['mean'].mean()

3.6900000000000004

In [7]:
with open('image_ratings.tex','w') as rf:
    rf.write(image_ratings_df.to_latex(index=True))

In [8]:
subjects_df = pd.read_csv('Experiment check list - subjects.tsv', delimiter='\t')
subjects_df = subjects_df.join(survey_df)
subjects_df

,ID number,name,consent form,lights,TOBII ID,RecordingID,Duration (seconds),Weighted Gaze Samples (%),Gaze Samples (%),callibration,...,image 1 - face,image 2 - face,image 3 - face,image 4 - face,image 5 - face,image 6 - face,image 7 - face,image 8 - face,image 9 - face,image 10 - face
0,P001,Kornelija,n,"close window, full indoor",P001,Rec 01,457.8,63,64,y,...,5,4,4,5,3,2,3,4,4,3
1,P002,Clara,y,"close window, full indoor",P002,E_P002_rec01,492.4,60,62,y,...,5,4,4,2,1,5,3,1,1,4
2,P003,Tereza,y,"close window, full indoor",P003,F_p003_rec1,411.6,43,43,y,...,5,5,5,5,5,5,3,5,5,3
3,P004,NaN,y,"close window, full indoor",P004,A_p004_rec1,407.4,47,50,y,...,5,5,5,5,4,5,5,5,4,5
4,P005,NaN,y,"close window, full indoor",P005,B_p005_rec1,367.1,7,7,y,...,4,4,3,2,3,1,3,2,2,1
5,P006,NaN,y,"close window, full indoor",P006,C_p006_01,347.8,14,14,y,...,5,4,5,4,4,2,2,3,3,1
6,P007,NaN,y,"close window, full indoor",P007,D_p007_rec1,360.1,93,93,y,...,5,5,5,4,5,4,3,3,3,3
7,P008,NaN,y,"close window, full indoor",P008,E_p008_rec1,410.4,18,19,y,...,5,5,4,4,5,5,3,2,4,2
8,P009,NaN,y,"close window, full indoor",P009,F_009_rec1,391.7,49,49,y,...,5,5,2,5,3,4,4,2,2,2
9,P010,NaN,y,"close window, full indoor",P010,A_P010_rec1,479.6,53,53,y,...,5,5,5,3,3,3,4,3,4,2
10,P011,NaN,y,"close window, full indoor",P011,B_P011,441.1,87,89,y,...,4,4,5,3,2,1,1,2,4,3
11,P012,NaN,y,"close window, full indoor",P012,C_P012,355.6,92,95,y,...,5,5,5,4,4,2,3,3,2,3
12,P013,NaN,y,"close window, full indoor",P013,D_P013,441.9,97,98,y,...,5,3,3,2,4,3,2,2,2,1
13,P014,NaN,y,"close window, full indoor",P014,E_P014,462.6,65,65,y,...,5,5,4,4,3,4,5,3,3,4
14,P015,NaN,y,"close window, full indoor",P015,F_P015,420.6,90,91,y,...,4,5,3,4,3,2,2,3,2,2
15,P016,NaN,y,"close window, full indoor",P016,A_P016,407.5,95,95,y,...,4,5,4,5,2,4,2,1,3,2
16,P017,NaN,y,"close window, full indoor",P017,B_Rec 03,353.3,15,15,y,...,5,5,4,5,3,3,3,2,2,3
17,P018,NaN,y,"close window, full indoor",P018,C_Rec 04,406.0,93,93,y,...,5,5,2,5,1,3,3,3,1,2
18,P019,NaN,y,"close window, full indoor",P019,D_P019,419.5,89,89,y,...,5,5,5,5,4,5,3,4,2,2
19,P020,NaN,y,"close window, full indoor",P020,E_P020,458.7,78,78,y,...,5,5,4,5,3,2,4,4,4,1
20,P021,NaN,y,"close window, full indoor",P021,F_P021,597.4,89,92,y,...,5,5,5,5,2,1,1,1,4,1
21,P022,NaN,y,"close window, full indoor",P022,A_22_REC1,414.3,83,86,y,...,5,5,5,5,5,5,5,5,5,5
22,P023,NaN,y,"close window, full indoor",P023,B_P023_REC1,421.4,89,89,y,...,5,5,5,2,3,2,4,4,3,4
23,P024,NaN,y,"close window, full indoor",P024,C_024_REC1,373.9,92,93,y,...,5,5,4,5,2,3,2,4,2,5
24,P025,NaN,y,"close window, full indoor",P025,D_025_REC1,335.2,94,97,y,...,4,4,3,4,4,3,3,2,3,2
25,P026,NaN,y,"close window, full indoor",P026,E_026_REC1,414.5,58,58,y,...,5,5,3,4,4,2,2,2,2,2
26,P027,NaN,y,"close window, full indoor",P027,F_026-REC1,397.3,95,96,y,...,5,5,5,5,5,5,5,5,5,5
27,P028,NaN,y,"close window, full indoor",P028,A_028-REC1,372.3,76,76,y,...,5,5,5,4,5,5,3,5,4,4
28,P029,NaN,y,"close window, full indoor",P029,B_029,353.1,94,94,y,...,5,5,5,5,5,5,5,3,2,3
29,P030,NaN,y,"close window, full indoor",P030,C_030-1,332.7,56,61,NaN,...,5,5,5,5,5,5,4,3,5,5

In [32]:
def get_image_name(x):
    match = re.match(r"(.+\.png)", x)
    if match is not None:
        #print(match.group(0))
        return '_'.join(match.group(0).split('.')[0].split('_')[2:])
    return None

def get_aoi_name(x):
    return x.split("_")[-2]

## First Fixation Duration

In [10]:
first_fixation_duration_df = pd.read_csv('summary-stats/First Fixation Duration.txt', delimiter='\t')
first_fixation_duration_df.head()

,Unnamed: 0,First Fixation Duration_14_5_car-front-seat.png_face_N,First Fixation Duration_14_5_car-front-seat.png_face_Mean,First Fixation Duration_14_5_car-front-seat.png_face_Max,First Fixation Duration_14_5_car-front-seat.png_face_Min,First Fixation Duration_14_5_car-front-seat.png_face_Sum,First Fixation Duration_14_5_car-front-seat.png_face_Median,First Fixation Duration_14_5_car-front-seat.png_face_Stdev,First Fixation Duration_14_5_car-front-seat.png_Rectangle 2_N,First Fixation Duration_14_5_car-front-seat.png_Rectangle 2_Mean,...,First Fixation Duration_57_9_furniture.png_Rectangle 3_Sum,First Fixation Duration_57_9_furniture.png_Rectangle 3_Median,First Fixation Duration_57_9_furniture.png_Rectangle 3_Stdev,First Fixation Duration_57_9_furniture.png_Not on AOI_N,First Fixation Duration_57_9_furniture.png_Not on AOI_Mean,First Fixation Duration_57_9_furniture.png_Not on AOI_Max,First Fixation Duration_57_9_furniture.png_Not on AOI_Min,First Fixation Duration_57_9_furniture.png_Not on AOI_Sum,First Fixation Duration_57_9_furniture.png_Not on AOI_Median,First Fixation Duration_57_9_furniture.png_Not on AOI_Stdev
0,P001,1,"0,22","0,22","0,22","0,22","0,22",-,1,"0,19",...,-,-,-,-,-,-,-,-,-,-
1,P002,1,"0,32","0,32","0,32","0,32","0,32",-,1,"0,01",...,"0,24","0,24",-,1,"0,17","0,17","0,17","0,17","0,17",-
2,P003,1,"0,39","0,39","0,39","0,39","0,39",-,-,-,...,"0,01","0,01",-,-,-,-,-,-,-,-
3,P004,1,"0,27","0,27","0,27","0,27","0,27",-,-,-,...,"0,25","0,25",-,1,"0,15","0,15","0,15","0,15","0,15",-
4,P005,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [11]:
first_fixation_dur_df = first_fixation_duration_df.melt(
    id_vars=first_fixation_duration_df.columns[0])
first_fixation_dur_df = first_fixation_dur_df.rename(columns={"Unnamed: 0": "ID number"})
first_fixation_dur_df['metric'] = 'First Fixation Duration'
first_fixation_dur_df['image_AOI_measure'] = first_fixation_dur_df[[
    'metric', 'variable']].apply(lambda x: re.sub(x[0]+'_', '', x[1]), axis=1)

first_fixation_dur_df['image'] = first_fixation_dur_df['image_AOI_measure'].apply(get_image_name)
first_fixation_dur_df['AOI'] = first_fixation_dur_df['image_AOI_measure'].apply(lambda x: x.split("_")[-2])
first_fixation_dur_df['measurement'] = first_fixation_dur_df['image_AOI_measure'].apply(lambda x: x.split("_")[-1])
first_fixation_dur_df

,ID number,variable,value,metric,image_AOI_measure,image,AOI,measurement
0,P001,First Fixation Duration_14_5_car-front-seat.pn...,1,First Fixation Duration,14_5_car-front-seat.png_face_N,5_car-front-seat,face,N
1,P002,First Fixation Duration_14_5_car-front-seat.pn...,1,First Fixation Duration,14_5_car-front-seat.png_face_N,5_car-front-seat,face,N
2,P003,First Fixation Duration_14_5_car-front-seat.pn...,1,First Fixation Duration,14_5_car-front-seat.png_face_N,5_car-front-seat,face,N
3,P004,First Fixation Duration_14_5_car-front-seat.pn...,1,First Fixation Duration,14_5_car-front-seat.png_face_N,5_car-front-seat,face,N
4,P005,First Fixation Duration_14_5_car-front-seat.pn...,-,First Fixation Duration,14_5_car-front-seat.png_face_N,5_car-front-seat,face,N
...,...,...,...,...,...,...,...,...
6722,P027,First Fixation Duration_57_9_furniture.png_Not...,-,First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,9_furniture,Not on AOI,Stdev
6723,P028,First Fixation Duration_57_9_furniture.png_Not...,-,First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,9_furniture,Not on AOI,Stdev
6724,P029,First Fixation Duration_57_9_furniture.png_Not...,-,First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,9_furniture,Not on AOI,Stdev
6725,P030,First Fixation Duration_57_9_furniture.png_Not...,-,First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,9_furniture,Not on AOI,Stdev
6726,All Recordings,First Fixation Duration_57_9_furniture.png_Not...,"0,11",First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,9_furniture,Not on AOI,Stdev

In [12]:
analysis_columns = ['ID number','image', 'AOI', 'metric', 'measurement','value','Sequence'] 
first_fixation_dur_seq_df = first_fixation_dur_df.join(subjects_df.set_index("ID number"), on="ID number", rsuffix='_subject')[analysis_columns]
first_fixation_dur_seq_df

,ID number,image,AOI,metric,measurement,value,Sequence
0,P001,5_car-front-seat,face,First Fixation Duration,N,1,A
1,P002,5_car-front-seat,face,First Fixation Duration,N,1,E
2,P003,5_car-front-seat,face,First Fixation Duration,N,1,F
3,P004,5_car-front-seat,face,First Fixation Duration,N,1,A
4,P005,5_car-front-seat,face,First Fixation Duration,N,-,B
...,...,...,...,...,...,...,...
6722,P027,9_furniture,Not on AOI,First Fixation Duration,Stdev,-,F
6723,P028,9_furniture,Not on AOI,First Fixation Duration,Stdev,-,A
6724,P029,9_furniture,Not on AOI,First Fixation Duration,Stdev,-,B
6725,P030,9_furniture,Not on AOI,First Fixation Duration,Stdev,-,C
6726,All Recordings,9_furniture,Not on AOI,First Fixation Duration,Stdev,"0,11",NaN

In [13]:
sequence_order_primer_type_df = sequence_order_primer_type_df[(sequence_order_primer_type_df['primer-type'] ==
                               'functional') | (sequence_order_primer_type_df['primer-type'] == 'emotional')][['Sequence name/ Order', 'primer-type', 'primed-image'
                                                                                                              ]]

In [14]:
aoi_data_with_primers_df = pd.merge(sequence_order_primer_type_df, first_fixation_dur_seq_df, left_on=[
         'Sequence name/ Order', 'primed-image'], right_on=['Sequence','image']).rename(columns={'value_y': 'value',
                                                                                                'value_x': 'primer-image-name'})

def clean_val(x):
    if isinstance(x, int):
        return x
    if x == '-':
        return None
    if ',' in x:
        return float(re.sub(',', '.', x))
    return float(x)
    

aoi_data_with_primers_df.value = aoi_data_with_primers_df.value.apply(clean_val)
aoi_data_with_primers_df[aoi_data_with_primers_df.image == '3_house'] .to_csv('test_results.csv') # test output
aoi_data_with_primers_df[aoi_data_with_primers_df['primer-type'] == 'functional']

,Sequence name/ Order,primer-type,primed-image,ID number,image,AOI,metric,measurement,value,Sequence
0,E,functional,3_house,P002,3_house,face,First Fixation Duration,N,1.0,E
1,E,functional,3_house,P008,3_house,face,First Fixation Duration,N,1.0,E
2,E,functional,3_house,P014,3_house,face,First Fixation Duration,N,1.0,E
3,E,functional,3_house,P020,3_house,face,First Fixation Duration,N,1.0,E
4,E,functional,3_house,P026,3_house,face,First Fixation Duration,N,1.0,E
...,...,...,...,...,...,...,...,...,...,...
5791,C,functional,7_coffee,P006,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C
5792,C,functional,7_coffee,P012,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C
5793,C,functional,7_coffee,P018,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C
5794,C,functional,7_coffee,P024,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C
5795,C,functional,7_coffee,P030,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C

In [15]:
emo_primers = aoi_data_with_primers_df[aoi_data_with_primers_df['primer-type'] == 'emotional']
funct_primers = aoi_data_with_primers_df[aoi_data_with_primers_df['primer-type'] == 'functional']

In [16]:
emo_primers.value

105     1.00
106     1.00
107     1.00
108     1.00
109     1.00
        ...
5875    0.16
5876     NaN
5877     NaN
5878     NaN
5879     NaN
Name: value, Length: 2828, dtype: float64

In [17]:
funct_primers

,Sequence name/ Order,primer-type,primed-image,ID number,image,AOI,metric,measurement,value,Sequence
0,E,functional,3_house,P002,3_house,face,First Fixation Duration,N,1.0,E
1,E,functional,3_house,P008,3_house,face,First Fixation Duration,N,1.0,E
2,E,functional,3_house,P014,3_house,face,First Fixation Duration,N,1.0,E
3,E,functional,3_house,P020,3_house,face,First Fixation Duration,N,1.0,E
4,E,functional,3_house,P026,3_house,face,First Fixation Duration,N,1.0,E
...,...,...,...,...,...,...,...,...,...,...
5791,C,functional,7_coffee,P006,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C
5792,C,functional,7_coffee,P012,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C
5793,C,functional,7_coffee,P018,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C
5794,C,functional,7_coffee,P024,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C
5795,C,functional,7_coffee,P030,7_coffee,Not on AOI,First Fixation Duration,Stdev,NaN,C

In [18]:
gb_cols = ['primed-image', 'AOI']
measurement = 'Mean'
metric = 'First Fixation Duration'
func_primers_gb_agg = funct_primers[funct_primers['measurement'] == measurement].groupby(
    gb_cols).agg({'image': 'size', 'value': 'mean'}).rename(columns={'image': 'count'})
func_primers_gb_agg['primer'] = 'functional'
func_primers_gb_agg

                              count     value      primer
primed-image     AOI
1_kitchen        Not on AOI      16  0.210000  functional
                 Rectangle 2     16  0.218462  functional
                 face            16  0.234286  functional
2_car-inside     Not on AOI      14  0.218182  functional
                 Rectangle 2     14  0.280000  functional
                 face            14  0.379286  functional
3_house          Not on AOI      16  0.150714  functional
                 Rectangle 2     16  0.510000  functional
                 face            16  0.459375  functional
4_floor-cleaner  Not on AOI      16  0.207692  functional
                 Rectangle 2     16  0.227000  functional
                 face            16  0.591333  functional
5_car-front-seat Not on AOI      16  0.144286  functional
                 Rectangle 2     16  0.233333  functional
                 face            16  0.261250  functional
6_bag            Not on AOI      14  0.175000  functional
                 Rectangle 2     14  0.429167  functional
                 face            14  0.345385  functional
7_coffee         Not on AOI      16  0.161538  functional
                 Rectangle 2     16  0.220000  functional
                 face            16  0.546000  functional
8_instrument     Not on AOI      16  0.185385  functional
                 Rectangle 3     16  0.172143  functional
                 face            16  0.227333  functional
9_furniture      Not on AOI      16  0.160667  functional
                 Rectangle 2     16  0.263846  functional
                 Rectangle 3     16  0.244286  functional
                 face            16  0.326000  functional

In [19]:
emo_primers_gb_agg = emo_primers[emo_primers['measurement'] == measurement].groupby(
    gb_cols).mean()
emo_primers_gb_agg['primer'] = 'emotional'
aggregate_scores_both_primers = emo_primers_gb_agg.append(func_primers_gb_agg)
aggregate_scores_both_primers['measurement'] = measurement
aggregate_scores_both_primers['aggregate'] = 'mean'
aggregate_scores_both_primers['metric'] = metric
aggregate_scores_both_primers

/Users/sallyisa/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

                              count      primer     value measurement  \
primed-image     AOI
1_kitchen        Not on AOI     NaN   emotional  0.193636        Mean
                 Rectangle 2    NaN   emotional  0.310909        Mean
                 face           NaN   emotional  0.330000        Mean
2_car-inside     Not on AOI     NaN   emotional  0.129167        Mean
                 Rectangle 2    NaN   emotional  0.230000        Mean
                 face           NaN   emotional  0.318667        Mean
3_house          Not on AOI     NaN   emotional  0.170000        Mean
                 Rectangle 2    NaN   emotional  0.377273        Mean
                 face           NaN   emotional  0.375714        Mean
4_floor-cleaner  Not on AOI     NaN   emotional  0.227857        Mean
                 Rectangle 2    NaN   emotional  0.278750        Mean
                 face           NaN   emotional  0.765000        Mean
5_car-front-seat Not on AOI     NaN   emotional  0.185833        Mean
                 Rectangle 2    NaN   emotional  0.726250        Mean
                 face           NaN   emotional  0.460833        Mean
6_bag            Not on AOI     NaN   emotional  0.188333        Mean
                 Rectangle 2    NaN   emotional  0.248000        Mean
                 face           NaN   emotional  0.273077        Mean
7_coffee         Not on AOI     NaN   emotional  0.210000        Mean
                 Rectangle 2    NaN   emotional  0.510000        Mean
                 face           NaN   emotional  0.596429        Mean
8_instrument     Not on AOI     NaN   emotional  0.176154        Mean
                 Rectangle 3    NaN   emotional  0.231538        Mean
                 face           NaN   emotional  0.291538        Mean
9_furniture      Not on AOI     NaN   emotional  0.249000        Mean
                 Rectangle 2    NaN   emotional  0.310000        Mean
                 Rectangle 3    NaN   emotional  0.230000        Mean
                 face           NaN   emotional  0.285714        Mean
1_kitchen        Not on AOI    16.0  functional  0.210000        Mean
                 Rectangle 2   16.0  functional  0.218462        Mean
                 face          16.0  functional  0.234286        Mean
2_car-inside     Not on AOI    14.0  functional  0.218182        Mean
                 Rectangle 2   14.0  functional  0.280000        Mean
                 face          14.0  functional  0.379286        Mean
3_house          Not on AOI    16.0  functional  0.150714        Mean
                 Rectangle 2   16.0  functional  0.510000        Mean
                 face          16.0  functional  0.459375        Mean
4_floor-cleaner  Not on AOI    16.0  functional  0.207692        Mean
                 Rectangle 2   16.0  functional  0.227000        Mean
                 face          16.0  functional  0.591333        Mean
5_car-front-seat Not on AOI    16.0  functional  0.144286        Mean
                 Rectangle 2   16.0  functional  0.233333        Mean
                 face          16.0  functional  0.261250        Mean
6_bag            Not on AOI    14.0  functional  0.175000        Mean
                 Rectangle 2   14.0  functional  0.429167        Mean
                 face          14.0  functional  0.345385        Mean
7_coffee         Not on AOI    16.0  functional  0.161538        Mean
                 Rectangle 2   16.0  functional  0.220000        Mean
                 face          16.0  functional  0.546000        Mean
8_instrument     Not on AOI    16.0  functional  0.185385        Mean
                 Rectangle 3   16.0  functional  0.172143        Mean
                 face          16.0  functional  0.227333        Mean
9_furniture      Not on AOI    16.0  functional  0.160667        Mean
                 Rectangle 2   16.0  functional  0.263846        Mean
                 Rectangle 3   16.0  functional  0.244286        Mean
                 face          16.0  functional  0.326000        Mean

                             aggregate                   metric
primed-image     AOI
1_kitchen        Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
2_car-inside     Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
3_house          Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
4_floor-cleaner  Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
5_car-front-seat Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
6_bag            Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
7_coffee         Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
8_instrument     Not on AOI       mean  First Fixation Duration
                 Rectangle 3      mean  First Fixation Duration
                 face             mean  First Fixation Duration
9_furniture      Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 Rectangle 3      mean  First Fixation Duration
                 face             mean  First Fixation Duration
1_kitchen        Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
2_car-inside     Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
3_house          Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
4_floor-cleaner  Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
5_car-front-seat Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
6_bag            Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
7_coffee         Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 face             mean  First Fixation Duration
8_instrument     Not on AOI       mean  First Fixation Duration
                 Rectangle 3      mean  First Fixation Duration
                 face             mean  First Fixation Duration
9_furniture      Not on AOI       mean  First Fixation Duration
                 Rectangle 2      mean  First Fixation Duration
                 Rectangle 3      mean  First Fixation Duration
                 face             mean  First Fixation Duration

In [20]:
emo_primers[emo_primers['measurement'] == 'Mean'].groupby('primed-image').count()

,Sequence name/ Order,primer-type,ID number,image,AOI,metric,measurement,value,Sequence
primed-image,,,,,,,,,
1_kitchen,42,42,42,42,42,42,42,36,42
2_car-inside,48,48,48,48,48,48,48,42,48
3_house,42,42,42,42,42,42,42,35,42
4_floor-cleaner,42,42,42,42,42,42,42,36,42
5_car-front-seat,42,42,42,42,42,42,42,32,42
6_bag,48,48,48,48,48,48,48,35,48
7_coffee,42,42,42,42,42,42,42,24,42
8_instrument,42,42,42,42,42,42,42,39,42
9_furniture,56,56,56,56,56,56,56,43,56

In [21]:
emo_primers[emo_primers['measurement'] == 'Mean'].groupby('primed-image').mean()

                     value
primed-image
1_kitchen         0.282500
2_car-inside      0.232857
3_house           0.317429
4_floor-cleaner   0.448056
5_car-front-seat  0.424062
6_bag             0.236857
7_coffee          0.447917
8_instrument      0.233077
9_furniture       0.273023

In [22]:
sequence_order_primer_type_df

     Sequence name/ Order primer-type       primed-image
0                       A  functional  4_floor-cleaner-4
1                       B   emotional  4_floor-cleaner-4
2                       C   emotional     2_car-inside-3
3                       D  functional     2_car-inside-3
4                       E  functional  4_floor-cleaner-4
...                   ...         ...                ...
1699                    H  functional     2_car-inside-3
1700                    I  functional          1_kitchen
1701                    J   emotional          1_kitchen
1702                    K  functional  4_floor-cleaner-1
1703                    L   emotional  4_floor-cleaner-1

[576 rows x 3 columns]

In [34]:
def analyze_measture(measure_name, measurement):
    tobii_measure_df = pd.read_csv(
        'summary-stats/{}.txt'.format(measure_name), delimiter='\t')
    tobii_measure_df = tobii_measure_df.melt(
        id_vars=tobii_measure_df.columns[0])
    tobii_measure_df = tobii_measure_df.rename(
        columns={"Unnamed: 0": "ID number"})
    tobii_measure_df['metric'] = measure_name
    tobii_measure_df['image_AOI_measure'] = tobii_measure_df[[
        'metric', 'variable']].apply(lambda x: re.sub(x[0]+'_', '', x[1]), axis=1)
    tobii_measure_df['image'] = tobii_measure_df['image_AOI_measure'].apply(
        get_image_name)
    tobii_measure_df['AOI'] = tobii_measure_df['image_AOI_measure'].apply(
        lambda x: x.split("_")[-2])
    tobii_measure_df['measurement'] = tobii_measure_df['image_AOI_measure'].apply(
        lambda x: x.split("_")[-1])
    # return tobii_measure_df
    analysis_columns = ['ID number', 'image', 'AOI',
                        'metric', 'measurement', 'value', 'Sequence']
    tobii_measure_seq_df = tobii_measure_df.join(subjects_df.set_index(
        "ID number"), on="ID number", rsuffix='_subject')[analysis_columns]
    tobii_measure_seq_df.to_csv('test_results.csv')
    # return tobii_measure_seq_df
    #return sequence_order_primer_type_df, tobii_measure_df
    aoi_data_with_primers_df = pd.merge(sequence_order_primer_type_df, tobii_measure_seq_df, left_on=[
        'Sequence name/ Order', 'primed-image'], right_on=['Sequence', 'image']).rename(columns={'value_y': 'value',
                                                                                                 'value_x': 'primer-image-name'})
    #return tobii_measure_seq_df, aoi_data_with_primers_df
    def clean_val(x):
        if isinstance(x, int):
            return x
        if x == '-':
            return None
        if ',' in x:
            return float(re.sub(',', '.', x))
        return float(x)

    aoi_data_with_primers_df.value = aoi_data_with_primers_df.value.apply(
        clean_val)
    #return aoi_data_with_primers_df
    emo_primers= aoi_data_with_primers_df[aoi_data_with_primers_df['primer-type'] == 'emotional']
    funct_primers= aoi_data_with_primers_df[aoi_data_with_primers_df['primer-type'] == 'functional']

    gb_cols= ['primed-image', 'AOI']
    func_primers_gb_agg= funct_primers[funct_primers['measurement'] == measurement].groupby(
        gb_cols).agg({'image': 'size', 'value': 'mean'}).rename(columns={'image': 'count'})
    func_primers_gb_agg['primer']= 'functional'
    func_primers_gb_agg

    emo_primers_gb_agg= emo_primers[emo_primers['measurement'] == measurement].groupby(
        gb_cols).mean()
    emo_primers_gb_agg['primer']= 'emotional'
    aggregate_scores_both_primers= emo_primers_gb_agg.append(
        func_primers_gb_agg)
    aggregate_scores_both_primers['measurement']= measurement
    aggregate_scores_both_primers['aggregate']= measurement.lower()
    aggregate_scores_both_primers['metric']= measure_name

    emo_primers[emo_primers['measurement'] ==
                'Mean'].groupby('primed-image').count()

    emo_primers[emo_primers['measurement'] ==
                'Mean'].groupby('primed-image').mean()
    return aggregate_scores_both_primers

primers = analyze_measture('Time to First Fixation (Across Media)', 'Mean')
primers

                              count      primer      value measurement  \
primed-image     AOI
1_kitchen        Not on AOI     NaN   emotional   0.029091        Mean
                 Rectangle 2    NaN   emotional  12.870909        Mean
                 face           NaN   emotional   1.716429        Mean
2_car-inside     Not on AOI     NaN   emotional   0.076667        Mean
                 Rectangle 2    NaN   emotional   0.623333        Mean
                 face           NaN   emotional   0.764000        Mean
3_house          Not on AOI     NaN   emotional   0.235000        Mean
                 Rectangle 2    NaN   emotional   1.319091        Mean
                 face           NaN   emotional   0.346429        Mean
4_floor-cleaner  Not on AOI     NaN   emotional   0.055000        Mean
                 Rectangle 2    NaN   emotional   1.826250        Mean
                 face           NaN   emotional   0.355000        Mean
5_car-front-seat Not on AOI     NaN   emotional   0.190000        Mean
                 Rectangle 2    NaN   emotional   1.587500        Mean
                 face           NaN   emotional   0.335000        Mean
6_bag            Not on AOI     NaN   emotional   0.226667        Mean
                 Rectangle 2    NaN   emotional   2.059000        Mean
                 face           NaN   emotional   0.254615        Mean
7_coffee         Not on AOI     NaN   emotional   0.304444        Mean
                 Rectangle 2    NaN   emotional   1.990000        Mean
                 face           NaN   emotional   0.272857        Mean
8_instrument     Not on AOI     NaN   emotional   0.193077        Mean
                 Rectangle 3    NaN   emotional   0.874615        Mean
                 face           NaN   emotional   0.730769        Mean
9_furniture      Not on AOI     NaN   emotional   0.746000        Mean
                 Rectangle 2    NaN   emotional   1.422727        Mean
                 Rectangle 3    NaN   emotional   1.342500        Mean
                 face           NaN   emotional   0.331429        Mean
1_kitchen        Not on AOI    16.0  functional   0.417143        Mean
                 Rectangle 2   16.0  functional   1.155385        Mean
                 face          16.0  functional   0.690000        Mean
2_car-inside     Not on AOI    14.0  functional   1.006364        Mean
                 Rectangle 2   14.0  functional   0.899231        Mean
                 face          14.0  functional   0.571429        Mean
3_house          Not on AOI    16.0  functional   0.140000        Mean
                 Rectangle 2   16.0  functional   1.719231        Mean
                 face          16.0  functional   0.464375        Mean
4_floor-cleaner  Not on AOI    16.0  functional   0.428462        Mean
                 Rectangle 2   16.0  functional   0.735000        Mean
                 face          16.0  functional   0.488000        Mean
5_car-front-seat Not on AOI    16.0  functional   0.147143        Mean
                 Rectangle 2   16.0  functional   1.033333        Mean
                 face          16.0  functional   0.360000        Mean
6_bag            Not on AOI    14.0  functional   0.171667        Mean
                 Rectangle 2   14.0  functional   0.994167        Mean
                 face          14.0  functional   0.296923        Mean
7_coffee         Not on AOI    16.0  functional   0.397692        Mean
                 Rectangle 2   16.0  functional   0.100000        Mean
                 face          16.0  functional   0.329333        Mean
8_instrument     Not on AOI    16.0  functional   0.300769        Mean
                 Rectangle 3   16.0  functional   0.475714        Mean
                 face          16.0  functional   0.624000        Mean
9_furniture      Not on AOI    16.0  functional   0.277333        Mean
                 Rectangle 2   16.0  functional   2.059231        Mean
                 Rectangle 3   16.0  functional   1.585714        Mean
                 face          16.0  functional   0.566000        Mean

                             aggregate                                 metric
primed-image     AOI
1_kitchen        Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
2_car-inside     Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
3_house          Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
4_floor-cleaner  Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
5_car-front-seat Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
6_bag            Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
7_coffee         Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
8_instrument     Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 3      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
9_furniture      Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 Rectangle 3      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
1_kitchen        Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
2_car-inside     Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
3_house          Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
4_floor-cleaner  Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
5_car-front-seat Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
6_bag            Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
7_coffee         Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
8_instrument     Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 3      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)
9_furniture      Not on AOI       mean  Time to First Fixation (Across Media)
                 Rectangle 2      mean  Time to First Fixation (Across Media)
                 Rectangle 3      mean  Time to First Fixation (Across Media)
                 face             mean  Time to First Fixation (Across Media)

In [24]:
seqs

     Sequence name/ Order primer-type       primed-image
0                       A  functional  4_floor-cleaner-4
1                       B   emotional  4_floor-cleaner-4
2                       C   emotional     2_car-inside-3
3                       D  functional     2_car-inside-3
4                       E  functional  4_floor-cleaner-4
...                   ...         ...                ...
1699                    H  functional     2_car-inside-3
1700                    I  functional          1_kitchen
1701                    J   emotional          1_kitchen
1702                    K  functional  4_floor-cleaner-1
1703                    L   emotional  4_floor-cleaner-1

[576 rows x 3 columns]

In [25]:
sequence_order_primer_type_df

     Sequence name/ Order primer-type       primed-image
0                       A  functional  4_floor-cleaner-4
1                       B   emotional  4_floor-cleaner-4
2                       C   emotional     2_car-inside-3
3                       D  functional     2_car-inside-3
4                       E  functional  4_floor-cleaner-4
...                   ...         ...                ...
1699                    H  functional     2_car-inside-3
1700                    I  functional          1_kitchen
1701                    J   emotional          1_kitchen
1702                    K  functional  4_floor-cleaner-1
1703                    L   emotional  4_floor-cleaner-1

[576 rows x 3 columns]

In [26]:
primers

,ID number,image,AOI,metric,measurement,value,Sequence
0,P001,14_5_car-front-seat,face,Time to First Fixation (Across Media),N,1,A
1,P002,14_5_car-front-seat,face,Time to First Fixation (Across Media),N,1,E
2,P003,14_5_car-front-seat,face,Time to First Fixation (Across Media),N,1,F
3,P004,14_5_car-front-seat,face,Time to First Fixation (Across Media),N,1,A
4,P005,14_5_car-front-seat,face,Time to First Fixation (Across Media),N,-,B
...,...,...,...,...,...,...,...
6722,P027,57_9_furniture,Not on AOI,Time to First Fixation (Across Media),Stdev,-,F
6723,P028,57_9_furniture,Not on AOI,Time to First Fixation (Across Media),Stdev,-,A
6724,P029,57_9_furniture,Not on AOI,Time to First Fixation (Across Media),Stdev,-,B
6725,P030,57_9_furniture,Not on AOI,Time to First Fixation (Across Media),Stdev,-,C
6726,All Recordings,57_9_furniture,Not on AOI,Time to First Fixation (Across Media),Stdev,"1,06",NaN