In [1]:
import pandas as pd
import re

## Load Sequence Data 
To Determine Primers

In [2]:
sequences_df = pd.read_csv('sequences_all.tsv', delimiter='\t')
sequence_order_primer_type_df  = sequences_df.melt(id_vars= sequences_df.columns[0]) 
def funct_or_emo(string):
    if '-emo'in string:
        return 'emotional'
    if '-funct' in string:
        return 'functional'
    if '__' in string:
        return 'crosshair'
    return 'image'

def get_primed_image(string):
    if 'primer'in string:
        return re.search(r"-(?:emo|funct)-(.+)", string).group(1)
    return '_'.join(string.split('_')[1:])
sequence_order_primer_type_df['primer-type'] =  sequence_order_primer_type_df.value.apply(funct_or_emo)
sequence_order_primer_type_df['primed-image'] =  sequence_order_primer_type_df.value.apply(get_primed_image)
sequence_order_primer_type_df

,Sequence name/ Order,variable,value,primer-type,primed-image
0,A,0,0_primer-funct-4_floor-cleaner-4,functional,4_floor-cleaner-4
1,B,0,0_primer-emo-4_floor-cleaner-4,emotional,4_floor-cleaner-4
2,C,0,123_primer-emo-2_car-inside-3,emotional,2_car-inside-3
3,D,0,123_primer-funct-2_car-inside-3,functional,2_car-inside-3
4,E,0,0_primer-funct-4_floor-cleaner-4,functional,4_floor-cleaner-4
...,...,...,...,...,...
1723,H,143,125_2_car-inside-3,image,2_car-inside-3
1724,I,143,20_1_kitchen,image,1_kitchen
1725,J,143,20_1_kitchen,image,1_kitchen
1726,K,143,23_4_floor-cleaner-1,image,4_floor-cleaner-1
1727,L,143,23_4_floor-cleaner-1,image,4_floor-cleaner-1

In [3]:
sequences_df.columns[0]

'Sequence name/ Order'

In [4]:
survey_df = pd.read_csv('Experiment check list - survey responses.tsv', delimiter='\t')
survey_df.head()

,Timestamp,Please write your Subject ID number,What is your gender?,What is your age?,Are you wearing glasses or contact lenses?,What is your first language?,Are you currently enrolled in a Cognitive Science course?,image 1 - face,image 2 - face,image 3 - face,image 4 - face,image 5 - face,image 6 - face,image 7 - face,image 8 - face,image 9 - face,image 10 - face
0,11/13/2019 20:33:49,P001,Female,26,NaN,NaN,NaN,5,4,4,5,3,2,3,4,4,3
1,11/15/2019 9:18:27,P002,Female,24,I am wearing neither.,Danish,Yes,5,4,4,2,1,5,3,1,1,4
2,11/15/2019 10:00:40,P003,Female,24,I am wearing neither.,Danish,No,5,5,5,5,5,5,3,5,5,3
3,11/15/2019 12:14:16,P004,Female,26,I am wearing neither.,Danish,No,5,5,5,5,4,5,5,5,4,5
4,11/15/2019 12:18:23,P005,Female,24,I am wearing neither.,Lithuanian,Yes,4,4,3,2,3,1,3,2,2,1

## Survey Data
#### Get stats for image ratings

In [5]:
image_cols = [col for col in survey_df.columns if 'image' in col]
image_ratings_df = pd.DataFrame(survey_df[image_cols].mean()).rename(columns={0:'mean'})
image_ratings_df['median'] = survey_df[image_cols].median()
image_ratings_df['stdev'] = survey_df[image_cols].std()
image_ratings_df

                     mean  median     stdev
image 1 - face   4.833333     5.0  0.379049
image 2 - face   4.733333     5.0  0.520830
image 3 - face   4.200000     4.5  0.961321
image 4 - face   4.166667     4.5  1.053183
image 5 - face   3.500000     3.5  1.224745
image 6 - face   3.366667     3.0  1.425950
image 7 - face   3.166667     3.0  1.147211
image 8 - face   3.033333     3.0  1.245221
image 9 - face   3.066667     3.0  1.201532
image 10 - face  2.833333     3.0  1.341212

In [6]:
image_ratings_df['mean'].mean()

3.6900000000000004

In [7]:
with open('image_ratings.tex','w') as rf:
    rf.write(image_ratings_df.to_latex(index=True))

In [8]:
subjects_df = pd.read_csv('Experiment check list - subjects.tsv', delimiter='\t')
subjects_df = subjects_df.join(survey_df)
subjects_df

,ID number,name,consent form,lights,TOBII ID,RecordingID,Duration (seconds),Weighted Gaze Samples (%),Gaze Samples (%),callibration,...,image 1 - face,image 2 - face,image 3 - face,image 4 - face,image 5 - face,image 6 - face,image 7 - face,image 8 - face,image 9 - face,image 10 - face
0,P001,Kornelija,n,"close window, full indoor",P001,Rec 01,457.8,63,64,y,...,5,4,4,5,3,2,3,4,4,3
1,P002,Clara,y,"close window, full indoor",P002,E_P002_rec01,492.4,60,62,y,...,5,4,4,2,1,5,3,1,1,4
2,P003,Tereza,y,"close window, full indoor",P003,F_p003_rec1,411.6,43,43,y,...,5,5,5,5,5,5,3,5,5,3
3,P004,NaN,y,"close window, full indoor",P004,A_p004_rec1,407.4,47,50,y,...,5,5,5,5,4,5,5,5,4,5
4,P005,NaN,y,"close window, full indoor",P005,B_p005_rec1,367.1,7,7,y,...,4,4,3,2,3,1,3,2,2,1
5,P006,NaN,y,"close window, full indoor",P006,C_p006_01,347.8,14,14,y,...,5,4,5,4,4,2,2,3,3,1
6,P007,NaN,y,"close window, full indoor",P007,D_p007_rec1,360.1,93,93,y,...,5,5,5,4,5,4,3,3,3,3
7,P008,NaN,y,"close window, full indoor",P008,E_p008_rec1,410.4,18,19,y,...,5,5,4,4,5,5,3,2,4,2
8,P009,NaN,y,"close window, full indoor",P009,F_009_rec1,391.7,49,49,y,...,5,5,2,5,3,4,4,2,2,2
9,P010,NaN,y,"close window, full indoor",P010,A_P010_rec1,479.6,53,53,y,...,5,5,5,3,3,3,4,3,4,2
10,P011,NaN,y,"close window, full indoor",P011,B_P011,441.1,87,89,y,...,4,4,5,3,2,1,1,2,4,3
11,P012,NaN,y,"close window, full indoor",P012,C_P012,355.6,92,95,y,...,5,5,5,4,4,2,3,3,2,3
12,P013,NaN,y,"close window, full indoor",P013,D_P013,441.9,97,98,y,...,5,3,3,2,4,3,2,2,2,1
13,P014,NaN,y,"close window, full indoor",P014,E_P014,462.6,65,65,y,...,5,5,4,4,3,4,5,3,3,4
14,P015,NaN,y,"close window, full indoor",P015,F_P015,420.6,90,91,y,...,4,5,3,4,3,2,2,3,2,2
15,P016,NaN,y,"close window, full indoor",P016,A_P016,407.5,95,95,y,...,4,5,4,5,2,4,2,1,3,2
16,P017,NaN,y,"close window, full indoor",P017,B_Rec 03,353.3,15,15,y,...,5,5,4,5,3,3,3,2,2,3
17,P018,NaN,y,"close window, full indoor",P018,C_Rec 04,406.0,93,93,y,...,5,5,2,5,1,3,3,3,1,2
18,P019,NaN,y,"close window, full indoor",P019,D_P019,419.5,89,89,y,...,5,5,5,5,4,5,3,4,2,2
19,P020,NaN,y,"close window, full indoor",P020,E_P020,458.7,78,78,y,...,5,5,4,5,3,2,4,4,4,1
20,P021,NaN,y,"close window, full indoor",P021,F_P021,597.4,89,92,y,...,5,5,5,5,2,1,1,1,4,1
21,P022,NaN,y,"close window, full indoor",P022,A_22_REC1,414.3,83,86,y,...,5,5,5,5,5,5,5,5,5,5
22,P023,NaN,y,"close window, full indoor",P023,B_P023_REC1,421.4,89,89,y,...,5,5,5,2,3,2,4,4,3,4
23,P024,NaN,y,"close window, full indoor",P024,C_024_REC1,373.9,92,93,y,...,5,5,4,5,2,3,2,4,2,5
24,P025,NaN,y,"close window, full indoor",P025,D_025_REC1,335.2,94,97,y,...,4,4,3,4,4,3,3,2,3,2
25,P026,NaN,y,"close window, full indoor",P026,E_026_REC1,414.5,58,58,y,...,5,5,3,4,4,2,2,2,2,2
26,P027,NaN,y,"close window, full indoor",P027,F_026-REC1,397.3,95,96,y,...,5,5,5,5,5,5,5,5,5,5
27,P028,NaN,y,"close window, full indoor",P028,A_028-REC1,372.3,76,76,y,...,5,5,5,4,5,5,3,5,4,4
28,P029,NaN,y,"close window, full indoor",P029,B_029,353.1,94,94,y,...,5,5,5,5,5,5,5,3,2,3
29,P030,NaN,y,"close window, full indoor",P030,C_030-1,332.7,56,61,NaN,...,5,5,5,5,5,5,4,3,5,5

In [9]:
def get_image_name(x):
    match = re.match(r"(.+\.(?:png|jpg))", x)
    if match is not None:
        #print(match.group(0))
        return '_'.join(match.group(0).split('.')[0].split('_')[2:])
    return None

def get_aoi_name(x):
    return x.split("_")[-2]

## First Fixation Duration

In [10]:
first_fixation_duration_df = pd.read_csv('summary-stats/First Fixation Duration.txt', delimiter='\t')
first_fixation_duration_df.head()

,Unnamed: 0,First Fixation Duration_14_5_car-front-seat.png_face_N,First Fixation Duration_14_5_car-front-seat.png_face_Mean,First Fixation Duration_14_5_car-front-seat.png_face_Max,First Fixation Duration_14_5_car-front-seat.png_face_Min,First Fixation Duration_14_5_car-front-seat.png_face_Sum,First Fixation Duration_14_5_car-front-seat.png_face_Median,First Fixation Duration_14_5_car-front-seat.png_face_Stdev,First Fixation Duration_14_5_car-front-seat.png_Rectangle 2_N,First Fixation Duration_14_5_car-front-seat.png_Rectangle 2_Mean,...,First Fixation Duration_57_9_furniture.png_Rectangle 3_Sum,First Fixation Duration_57_9_furniture.png_Rectangle 3_Median,First Fixation Duration_57_9_furniture.png_Rectangle 3_Stdev,First Fixation Duration_57_9_furniture.png_Not on AOI_N,First Fixation Duration_57_9_furniture.png_Not on AOI_Mean,First Fixation Duration_57_9_furniture.png_Not on AOI_Max,First Fixation Duration_57_9_furniture.png_Not on AOI_Min,First Fixation Duration_57_9_furniture.png_Not on AOI_Sum,First Fixation Duration_57_9_furniture.png_Not on AOI_Median,First Fixation Duration_57_9_furniture.png_Not on AOI_Stdev
0,P001,1,"0,22","0,22","0,22","0,22","0,22",-,1,"0,19",...,-,-,-,-,-,-,-,-,-,-
1,P002,1,"0,32","0,32","0,32","0,32","0,32",-,1,"0,01",...,"0,24","0,24",-,1,"0,17","0,17","0,17","0,17","0,17",-
2,P003,1,"0,39","0,39","0,39","0,39","0,39",-,-,-,...,"0,01","0,01",-,-,-,-,-,-,-,-
3,P004,1,"0,27","0,27","0,27","0,27","0,27",-,-,-,...,"0,25","0,25",-,1,"0,15","0,15","0,15","0,15","0,15",-
4,P005,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [11]:
first_fixation_dur_df = first_fixation_duration_df.melt(
    id_vars=first_fixation_duration_df.columns[0])
first_fixation_dur_df = first_fixation_dur_df.rename(columns={"Unnamed: 0": "ID number"})
first_fixation_dur_df['metric'] = 'First Fixation Duration'
first_fixation_dur_df['image_AOI_measure'] = first_fixation_dur_df[[
    'metric', 'variable']].apply(lambda x: re.sub(x[0]+'_', '', x[1]), axis=1)

first_fixation_dur_df['image'] = first_fixation_dur_df['image_AOI_measure'].apply(get_image_name)
first_fixation_dur_df['AOI'] = first_fixation_dur_df['image_AOI_measure'].apply(lambda x: x.split("_")[-2])
first_fixation_dur_df['measurement'] = first_fixation_dur_df['image_AOI_measure'].apply(lambda x: x.split("_")[-1])
first_fixation_dur_df

,ID number,variable,value,metric,image_AOI_measure,image,AOI,measurement
0,P001,First Fixation Duration_14_5_car-front-seat.pn...,1,First Fixation Duration,14_5_car-front-seat.png_face_N,car-front-seat,face,N
1,P002,First Fixation Duration_14_5_car-front-seat.pn...,1,First Fixation Duration,14_5_car-front-seat.png_face_N,car-front-seat,face,N
2,P003,First Fixation Duration_14_5_car-front-seat.pn...,1,First Fixation Duration,14_5_car-front-seat.png_face_N,car-front-seat,face,N
3,P004,First Fixation Duration_14_5_car-front-seat.pn...,1,First Fixation Duration,14_5_car-front-seat.png_face_N,car-front-seat,face,N
4,P005,First Fixation Duration_14_5_car-front-seat.pn...,-,First Fixation Duration,14_5_car-front-seat.png_face_N,car-front-seat,face,N
...,...,...,...,...,...,...,...,...
6722,P027,First Fixation Duration_57_9_furniture.png_Not...,-,First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,furniture,Not on AOI,Stdev
6723,P028,First Fixation Duration_57_9_furniture.png_Not...,-,First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,furniture,Not on AOI,Stdev
6724,P029,First Fixation Duration_57_9_furniture.png_Not...,-,First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,furniture,Not on AOI,Stdev
6725,P030,First Fixation Duration_57_9_furniture.png_Not...,-,First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,furniture,Not on AOI,Stdev
6726,All Recordings,First Fixation Duration_57_9_furniture.png_Not...,"0,11",First Fixation Duration,57_9_furniture.png_Not on AOI_Stdev,furniture,Not on AOI,Stdev

In [12]:
analysis_columns = ['ID number','image', 'AOI', 'metric', 'measurement','value','Sequence'] 
first_fixation_dur_seq_df = first_fixation_dur_df.join(subjects_df.set_index("ID number"), on="ID number", rsuffix='_subject')[analysis_columns]
first_fixation_dur_seq_df

,ID number,image,AOI,metric,measurement,value,Sequence
0,P001,car-front-seat,face,First Fixation Duration,N,1,A
1,P002,car-front-seat,face,First Fixation Duration,N,1,E
2,P003,car-front-seat,face,First Fixation Duration,N,1,F
3,P004,car-front-seat,face,First Fixation Duration,N,1,A
4,P005,car-front-seat,face,First Fixation Duration,N,-,B
...,...,...,...,...,...,...,...
6722,P027,furniture,Not on AOI,First Fixation Duration,Stdev,-,F
6723,P028,furniture,Not on AOI,First Fixation Duration,Stdev,-,A
6724,P029,furniture,Not on AOI,First Fixation Duration,Stdev,-,B
6725,P030,furniture,Not on AOI,First Fixation Duration,Stdev,-,C
6726,All Recordings,furniture,Not on AOI,First Fixation Duration,Stdev,"0,11",NaN

In [13]:
sequence_order_primer_type_df = sequence_order_primer_type_df[(sequence_order_primer_type_df['primer-type'] ==
                               'functional') | (sequence_order_primer_type_df['primer-type'] == 'emotional')][['Sequence name/ Order', 'primer-type', 'primed-image'
                                                                                                              ]]

In [14]:
aoi_data_with_primers_df = pd.merge(sequence_order_primer_type_df, first_fixation_dur_seq_df, left_on=[
         'Sequence name/ Order', 'primed-image'], right_on=['Sequence','image']).rename(columns={'value_y': 'value',
                                                                                                'value_x': 'primer-image-name'})

def clean_val(x):
    if isinstance(x, int):
        return x
    if x == '-':
        return None
    if ',' in x:
        return float(re.sub(',', '.', x))
    return float(x)

Empty DataFrame
Columns: [Sequence name/ Order, primer-type, primed-image, ID number, image, AOI, metric, measurement, value, Sequence]
Index: []

In [19]:
def analyze_measture(measure_name, measurement):
    tobii_measure_df = pd.read_csv(
        'summary-stats/{}.txt'.format(measure_name), delimiter='\t')
    tobii_measure_df = tobii_measure_df.melt(
        id_vars=tobii_measure_df.columns[0])
    tobii_measure_df = tobii_measure_df.rename(
        columns={"Unnamed: 0": "ID number"})
    tobii_measure_df['metric'] = measure_name
    tobii_measure_df['image_AOI_measure'] = tobii_measure_df[[
        'metric', 'variable']].apply(lambda x: re.sub(x[0]+'_', '', x[1]), axis=1)
    tobii_measure_df['image'] = tobii_measure_df['image_AOI_measure'].apply(
        get_image_name)
    tobii_measure_df['AOI'] = tobii_measure_df['image_AOI_measure'].apply(
        lambda x: x.split("_")[-2])
    tobii_measure_df['measurement'] = tobii_measure_df['image_AOI_measure'].apply(
        lambda x: x.split("_")[-1])
    # return tobii_measure_df
    analysis_columns = ['ID number', 'image', 'AOI',
                        'metric', 'measurement', 'value', 'Sequence']
    tobii_measure_seq_df = tobii_measure_df.join(subjects_df.set_index(
        "ID number"), on="ID number", rsuffix='_subject')[analysis_columns]
    tobii_measure_seq_df.to_csv('test_results.csv')
    # return tobii_measure_seq_df
    # return sequence_order_primer_type_df, tobii_measure_df
    aoi_data_with_primers_df = pd.merge(sequence_order_primer_type_df, tobii_measure_seq_df, left_on=[
        'Sequence name/ Order', 'primed-image'], right_on=['Sequence', 'image']).rename(columns={'value_y': 'value',
                                                                                                 'value_x': 'primer-image-name'})
    # return tobii_measure_seq_df, aoi_data_with_primers_df

    def clean_val(x):
        if isinstance(x, int):
            return x
        if x == '-':
            return None
        if ',' in x:
            return float(re.sub(',', '.', x))
        return float(x)

    aoi_data_with_primers_df.value = aoi_data_with_primers_df.value.apply(
        clean_val)
    # return aoi_data_with_primers_df
    emo_primers = aoi_data_with_primers_df[aoi_data_with_primers_df['primer-type'] == 'emotional']
    funct_primers = aoi_data_with_primers_df[aoi_data_with_primers_df['primer-type'] == 'functional']

    gb_cols = ['primed-image', 'AOI']
    func_primers_gb_agg = funct_primers[funct_primers['measurement'] == measurement].groupby(
        gb_cols).agg({'image': 'size', 'value': 'mean'}).rename(columns={'value': 'functional-val', 
                                                                         'image': 'num-datapoints-funct'})
    func_primers_gb_agg['primer'] = 'functional'
    func_primers_gb_agg

    emo_primers_gb_agg = emo_primers[emo_primers['measurement'] == measurement].groupby(
        gb_cols).agg({'image': 'size', 'value': 'mean'}).rename(columns={'value': 'emotional-val', 
                                                                         'image': 'num-datapoints-emo'})
    emo_primers_gb_agg['primer'] = 'emotional'
    aggregate_scores_both_primers = pd.concat([emo_primers_gb_agg,
        func_primers_gb_agg],axis=1, sort=False)
    aggregate_scores_both_primers['measurement'] = measurement
    aggregate_scores_both_primers['aggregate'] = measurement.lower()
    aggregate_scores_both_primers['metric'] = measure_name

    emo_primers[emo_primers['measurement'] ==
                'Mean'].groupby('primed-image').count()

    emo_primers[emo_primers['measurement'] ==
                'Mean'].groupby('primed-image').mean()
    return aoi_data_with_primers_df, aggregate_scores_both_primers


aoi_data_with_primers_df, agg_measure_both_primers = analyze_measture(
    'Time to First Fixation (Across Media)', 'Mean')
agg_measure_both_primers

                              num-datapoints-emo  emotional-val     primer  \
primed-image     AOI
10_boat          Not on AOI                   16       0.978333  emotional
                 Rectangle 2                  16       0.551333  emotional
                 face                         16       0.956923  emotional
1_kitchen        Not on AOI                   14       0.029091  emotional
                 Rectangle 2                  14      12.870909  emotional
                 face                         14       1.716429  emotional
2_car-inside     Not on AOI                   16       0.076667  emotional
                 Rectangle 2                  16       0.623333  emotional
                 face                         16       0.764000  emotional
3_house          Not on AOI                   14       0.235000  emotional
                 Rectangle 2                  14       1.319091  emotional
                 face                         14       0.346429  emotional
4_floor-cleaner  Not on AOI                   14       0.055000  emotional
                 Rectangle 2                  14       1.826250  emotional
                 face                         14       0.355000  emotional
5_car-front-seat Not on AOI                   14       0.190000  emotional
                 Rectangle 2                  14       1.587500  emotional
                 face                         14       0.335000  emotional
6_bag            Not on AOI                   16       0.226667  emotional
                 Rectangle 2                  16       2.059000  emotional
                 face                         16       0.254615  emotional
7_coffee         Not on AOI                   14       0.304444  emotional
                 Rectangle 2                  14       1.990000  emotional
                 face                         14       0.272857  emotional
8_instrument     Not on AOI                   14       0.193077  emotional
                 Rectangle 3                  14       0.874615  emotional
                 face                         14       0.730769  emotional
9_furniture      Not on AOI                   14       0.746000  emotional
                 Rectangle 2                  14       1.422727  emotional
                 Rectangle 3                  14       1.342500  emotional
                 face                         14       0.331429  emotional

                              num-datapoints-funct  functional-val  \
primed-image     AOI
10_boat          Not on AOI                     14        0.397500
                 Rectangle 2                    14        0.348462
                 face                           14        1.044167
1_kitchen        Not on AOI                     16        0.417143
                 Rectangle 2                    16        1.155385
                 face                           16        0.690000
2_car-inside     Not on AOI                     14        1.006364
                 Rectangle 2                    14        0.899231
                 face                           14        0.571429
3_house          Not on AOI                     16        0.140000
                 Rectangle 2                    16        1.719231
                 face                           16        0.464375
4_floor-cleaner  Not on AOI                     16        0.428462
                 Rectangle 2                    16        0.735000
                 face                           16        0.488000
5_car-front-seat Not on AOI                     16        0.147143
                 Rectangle 2                    16        1.033333
                 face                           16        0.360000
6_bag            Not on AOI                     14        0.171667
                 Rectangle 2                    14        0.994167
                 face                           14        0.296923
7_coffee         Not on AOI                     16        0.397692
                 Rectangle 2                    16        0.100000
                 face                           16        0.329333
8_instrument     Not on AOI                     16        0.300769
                 Rectangle 3                    16        0.475714
                 face                           16        0.624000
9_furniture      Not on AOI                     16        0.277333
                 Rectangle 2                    16        2.059231
                 Rectangle 3                    16        1.585714
                 face                           16        0.566000

                                  primer measurement aggregate  \
primed-image     AOI
10_boat          Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 face         functional        Mean      mean
1_kitchen        Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 face         functional        Mean      mean
2_car-inside     Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 face         functional        Mean      mean
3_house          Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 face         functional        Mean      mean
4_floor-cleaner  Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 face         functional        Mean      mean
5_car-front-seat Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 face         functional        Mean      mean
6_bag            Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 face         functional        Mean      mean
7_coffee         Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 face         functional        Mean      mean
8_instrument     Not on AOI   functional        Mean      mean
                 Rectangle 3  functional        Mean      mean
                 face         functional        Mean      mean
9_furniture      Not on AOI   functional        Mean      mean
                 Rectangle 2  functional        Mean      mean
                 Rectangle 3  functional        Mean      mean
                 face         functional        Mean      mean

                                                             metric
primed-image     AOI
10_boat          Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
1_kitchen        Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
2_car-inside     Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
3_house          Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
4_floor-cleaner  Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
5_car-front-seat Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
6_bag            Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
7_coffee         Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
8_instrument     Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 3  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)
9_furniture      Not on AOI   Time to First Fixation (Across Media)
                 Rectangle 2  Time to First Fixation (Across Media)
                 Rectangle 3  Time to First Fixation (Across Media)
                 face         Time to First Fixation (Across Media)

In [20]:
image_ratings_df = image_ratings_df.reset_index()

In [21]:
image_names = list(set(aoi_data_with_primers_df.image.tolist()))
image_names

['3_house',
 '2_car-inside',
 '4_floor-cleaner',
 '7_coffee',
 '6_bag',
 '8_instrument',
 '1_kitchen',
 '10_boat',
 '9_furniture',
 '5_car-front-seat']

In [22]:
for i in range(10):
    image_name = [s for s in image_names if str(i+1) in s][0]
    image_ratings_df.loc[image_ratings_df['index'] ==
                         "image {} - face".format(i+1), "image-name"] = image_name
image_ratings_df = image_ratings_df.rename(
    columns={"mean": "image-face-rating-mean", "median": "image-face-rating-median",
             "stdev": "image-face-rating-stdev"}).set_index("image-name")
image_ratings_df = image_ratings_df[[x for x in image_ratings_df.columns if x != 'index']]
image_ratings_df

,image-face-rating-mean,image-face-rating-median,image-face-rating-stdev
image-name,,,
1_kitchen,4.833333,5.0,0.379049
2_car-inside,4.733333,5.0,0.520830
3_house,4.200000,4.5,0.961321
4_floor-cleaner,4.166667,4.5,1.053183
5_car-front-seat,3.500000,3.5,1.224745
6_bag,3.366667,3.0,1.425950
7_coffee,3.166667,3.0,1.147211
8_instrument,3.033333,3.0,1.245221
9_furniture,3.066667,3.0,1.201532
10_boat,2.833333,3.0,1.341212

In [24]:
firsts = agg_measure_both_primers.index.get_level_values('primed-image')
agg_measure_both_primers['image-face-rating-mean'] = image_ratings_df.loc[firsts].values[:, 0]
agg_measure_both_primers['image-face-rating-median'] = image_ratings_df.loc[firsts].values[:, 1]
agg_measure_both_primers['image-face-rating-stdev'] = image_ratings_df.loc[firsts].values[:, 2]
agg_measure_both_primers.head(10)

                          num-datapoints-emo  emotional-val     primer  \
primed-image AOI
10_boat      Not on AOI                   16       0.978333  emotional
             Rectangle 2                  16       0.551333  emotional
             face                         16       0.956923  emotional
1_kitchen    Not on AOI                   14       0.029091  emotional
             Rectangle 2                  14      12.870909  emotional
             face                         14       1.716429  emotional
2_car-inside Not on AOI                   16       0.076667  emotional
             Rectangle 2                  16       0.623333  emotional
             face                         16       0.764000  emotional
3_house      Not on AOI                   14       0.235000  emotional

                          num-datapoints-funct  functional-val      primer  \
primed-image AOI
10_boat      Not on AOI                     14        0.397500  functional
             Rectangle 2                    14        0.348462  functional
             face                           14        1.044167  functional
1_kitchen    Not on AOI                     16        0.417143  functional
             Rectangle 2                    16        1.155385  functional
             face                           16        0.690000  functional
2_car-inside Not on AOI                     14        1.006364  functional
             Rectangle 2                    14        0.899231  functional
             face                           14        0.571429  functional
3_house      Not on AOI                     16        0.140000  functional

                         measurement aggregate  \
primed-image AOI
10_boat      Not on AOI         Mean      mean
             Rectangle 2        Mean      mean
             face               Mean      mean
1_kitchen    Not on AOI         Mean      mean
             Rectangle 2        Mean      mean
             face               Mean      mean
2_car-inside Not on AOI         Mean      mean
             Rectangle 2        Mean      mean
             face               Mean      mean
3_house      Not on AOI         Mean      mean

                                                         metric  \
primed-image AOI
10_boat      Not on AOI   Time to First Fixation (Across Media)
             Rectangle 2  Time to First Fixation (Across Media)
             face         Time to First Fixation (Across Media)
1_kitchen    Not on AOI   Time to First Fixation (Across Media)
             Rectangle 2  Time to First Fixation (Across Media)
             face         Time to First Fixation (Across Media)
2_car-inside Not on AOI   Time to First Fixation (Across Media)
             Rectangle 2  Time to First Fixation (Across Media)
             face         Time to First Fixation (Across Media)
3_house      Not on AOI   Time to First Fixation (Across Media)

                          image-face-rating-mean  image-face-rating-median  \
primed-image AOI
10_boat      Not on AOI                 2.833333                       3.0
             Rectangle 2                2.833333                       3.0
             face                       2.833333                       3.0
1_kitchen    Not on AOI                 4.833333                       5.0
             Rectangle 2                4.833333                       5.0
             face                       4.833333                       5.0
2_car-inside Not on AOI                 4.733333                       5.0
             Rectangle 2                4.733333                       5.0
             face                       4.733333                       5.0
3_house      Not on AOI                 4.200000                       4.5

                          image-face-rating-stdev
primed-image AOI
10_boat      Not on AOI                  1.341212
             Rectangle 2                 1.341212
             face                        1.341212
1_kitchen    Not on AOI                  0.379049
             Rectangle 2                 0.379049
             face                        0.379049
2_car-inside Not on AOI                  0.520830
             Rectangle 2                 0.520830
             face                        0.520830
3_house      Not on AOI                  0.961321

## Subject by subject measures:
Calculate for each subject, which AOI was looked at first. Then aggregate based on primer type.

In [72]:
all_subjects_aois_df = pd.merge(aoi_data_with_primers_df, image_ratings_df,
                                left_on='primed-image', right_on='image-name')  # .groupby('ID number')
all_subjects_aois_df = all_subjects_aois_df[all_subjects_aois_df.measurement == 'Mean'].sort_values(['image', 'primer-type','ID number'])
all_subjects_aois_df

,Sequence name/ Order,primer-type,primed-image,ID number,image,AOI,metric,measurement,value,Sequence,image-face-rating-mean,image-face-rating-median,image-face-rating-stdev
5256,A,emotional,10_boat,P001,10_boat,face,Time to First Fixation (Across Media),Mean,NaN,A,2.833333,3.0,1.341212
5298,A,emotional,10_boat,P001,10_boat,Rectangle 2,Time to First Fixation (Across Media),Mean,0.01,A,2.833333,3.0,1.341212
5340,A,emotional,10_boat,P001,10_boat,Not on AOI,Time to First Fixation (Across Media),Mean,0.00,A,2.833333,3.0,1.341212
5675,E,emotional,10_boat,P002,10_boat,face,Time to First Fixation (Across Media),Mean,0.50,E,2.833333,3.0,1.341212
5710,E,emotional,10_boat,P002,10_boat,Rectangle 2,Time to First Fixation (Across Media),Mean,NaN,E,2.833333,3.0,1.341212
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1929,A,functional,9_furniture,P028,9_furniture,Not on AOI,Time to First Fixation (Across Media),Mean,0.00,A,3.066667,3.0,1.201532
1269,C,functional,9_furniture,P030,9_furniture,face,Time to First Fixation (Across Media),Mean,0.17,C,3.066667,3.0,1.201532
1304,C,functional,9_furniture,P030,9_furniture,Rectangle 2,Time to First Fixation (Across Media),Mean,1.36,C,3.066667,3.0,1.201532
1339,C,functional,9_furniture,P030,9_furniture,Rectangle 3,Time to First Fixation (Across Media),Mean,0.72,C,3.066667,3.0,1.201532
1374,C,functional,9_furniture,P030,9_furniture,Not on AOI,Time to First Fixation (Across Media),Mean,0.00,C,3.066667,3.0,1.201532

In [84]:
idx_cols = [ 'image', 'primer-type','AOI', 'ID number']
pivot_df = all_subjects_aois_df.set_index(idx_cols)
pivot_df['value']

image        primer-type  AOI          ID number
10_boat      emotional    face         P001          NaN
                          Rectangle 2  P001         0.01
                          Not on AOI   P001         0.00
                          face         P002         0.50
                          Rectangle 2  P002          NaN
                                                    ...
9_furniture  functional   Not on AOI   P028         0.00
                          face         P030         0.17
                          Rectangle 2  P030         1.36
                          Rectangle 3  P030         0.72
                          Not on AOI   P030         0.00
Name: value, Length: 930, dtype: float64

In [109]:
image_ratings_df

,image-face-rating-mean,image-face-rating-median,image-face-rating-stdev
image-name,,,
1_kitchen,4.833333,5.0,0.379049
2_car-inside,4.733333,5.0,0.520830
3_house,4.200000,4.5,0.961321
4_floor-cleaner,4.166667,4.5,1.053183
5_car-front-seat,3.500000,3.5,1.224745
6_bag,3.366667,3.0,1.425950
7_coffee,3.166667,3.0,1.147211
8_instrument,3.033333,3.0,1.245221
9_furniture,3.066667,3.0,1.201532
10_boat,2.833333,3.0,1.341212

In [110]:
pivot_df = pivot_df['value'].unstack().transpose()

In [114]:
pivot_df

image          10_boat                                                 \
primer-type  emotional                   functional
AOI         Not on AOI Rectangle 2  face Not on AOI Rectangle 2  face
ID number
P001              0.00        0.01   NaN        NaN         NaN   NaN
P002              1.81         NaN  0.50        NaN         NaN   NaN
P003               NaN         NaN   NaN       0.17        0.47  3.04
P004              0.00        0.36  0.55        NaN         NaN   NaN
P005               NaN         NaN   NaN       0.56         NaN   NaN
P006               NaN        3.41   NaN        NaN         NaN   NaN
P007               NaN         NaN   NaN       0.00        1.07  0.17
P008               NaN        0.46  0.68        NaN         NaN   NaN
P009               NaN         NaN   NaN       0.92        0.05   NaN
P010              3.78        0.63  0.46        NaN         NaN   NaN
P011               NaN         NaN   NaN       2.66        0.27  0.37
P012              0.00        0.15  0.93        NaN         NaN   NaN
P013               NaN         NaN   NaN       0.00        0.41  0.19
P014               NaN        0.47  1.68        NaN         NaN   NaN
P015               NaN         NaN   NaN       0.00        0.42  2.36
P016               NaN        0.00  0.64        NaN         NaN   NaN
P017               NaN         NaN   NaN        NaN        0.49  0.73
P018              0.00        0.20  3.24        NaN         NaN   NaN
P019               NaN         NaN   NaN       0.00        0.52  0.28
P020              0.08        0.56  0.99        NaN         NaN   NaN
P021               NaN         NaN   NaN       0.46        0.00  1.97
P022              0.00        0.50  0.73        NaN         NaN   NaN
P023               NaN         NaN   NaN       0.00        0.48  2.13
P024              0.00        0.76  0.22        NaN         NaN   NaN
P025               NaN         NaN   NaN       0.00        0.16  0.85
P026              2.11        0.18  0.00        NaN         NaN   NaN
P027               NaN         NaN   NaN       0.00        0.19  0.19
P028              3.96        0.42   NaN        NaN         NaN   NaN
P029               NaN         NaN   NaN        NaN        0.00  0.25
P030              0.00        0.16  1.82        NaN         NaN   NaN

image        1_kitchen                                ... 8_instrument        \
primer-type  emotional                    functional  ...   functional
AOI         Not on AOI Rectangle 2   face Not on AOI  ...  Rectangle 3  face
ID number                                             ...
P001               NaN         NaN    NaN       0.00  ...         0.00  0.25
P002               NaN         NaN    NaN       0.06  ...         1.63  0.43
P003               NaN        0.52   0.67        NaN  ...          NaN   NaN
P004               NaN         NaN    NaN       0.00  ...         0.96  0.56
P005               NaN         NaN   1.73        NaN  ...          NaN   NaN
P006               NaN         NaN    NaN       1.79  ...          NaN   NaN
P007              0.00        0.29   0.96        NaN  ...          NaN   NaN
P008               NaN         NaN    NaN        NaN  ...         0.02  0.53
P009              0.32        0.00   0.70        NaN  ...          NaN   NaN
P010               NaN         NaN    NaN       1.32  ...         0.31  0.36
P011              0.00        0.27   1.21        NaN  ...          NaN   NaN
P012               NaN         NaN    NaN       0.28  ...         0.26  1.29
P013              0.00        0.17   0.30        NaN  ...          NaN   NaN
P014               NaN         NaN    NaN       1.94  ...         0.51  1.72
P015              0.00      138.18   0.50        NaN  ...          NaN   NaN
P016               NaN         NaN    NaN       0.00  ...         0.00  0.27
P017               NaN         NaN  15.33        NaN  ...          NaN   NaN
P018               NaN         NaN    NaN       0.00  ...         0.20  0.42
P019              0.00        0.13   0.59        NaN  ...          NaN   NaN
P020               NaN         NaN    NaN       0.00  ...         0.17  0.89
P021              0.00        1.15   0.20        NaN  ...          NaN   NaN
P022               NaN         NaN    NaN       0.38  ...         0.27  0.45
P023              0.00         NaN   0.25        NaN  ...          NaN   NaN
P024               NaN         NaN    NaN       0.00  ...          NaN  0.23
P025              0.00        0.13   0.44        NaN  ...          NaN   NaN
P026               NaN         NaN    NaN        NaN  ...         0.56  0.90
P027              0.00        0.27   0.98        NaN  ...          NaN   NaN
P028               NaN         NaN    NaN       0.07  ...         0.39  0.64
P029              0.00        0.47   0.17        NaN  ...          NaN   NaN
P030               NaN         NaN    NaN       0.00  ...         1.38  0.42

image       9_furniture                                                       \
primer-type   emotional                               functional
AOI          Not on AOI Rectangle 2 Rectangle 3  face Not on AOI Rectangle 2
ID number
P001                NaN         NaN         NaN   NaN        NaN         NaN
P002                NaN         NaN         NaN   NaN       0.90        0.63
P003                NaN        2.71        0.40  0.52        NaN         NaN
P004                NaN         NaN         NaN   NaN       0.00        3.57
P005                NaN         NaN         NaN  0.59        NaN         NaN
P006                NaN         NaN         NaN   NaN       2.79        1.06
P007               0.00        0.74         NaN  0.13        NaN         NaN
P008                NaN         NaN         NaN   NaN       0.41        3.58
P009               0.65        3.62        0.00  0.28        NaN         NaN
P010                NaN         NaN         NaN   NaN       0.06         NaN
P011               3.68        2.81        2.56  0.00        NaN         NaN
P012                NaN         NaN         NaN   NaN       0.00         NaN
P013               0.00        0.17        2.61  0.32        NaN         NaN
P014                NaN         NaN         NaN   NaN       0.00        3.16
P015               0.00        1.74        0.34  0.60        NaN         NaN
P016                NaN         NaN         NaN   NaN       0.00        3.73
P017                NaN        0.79         NaN  0.55        NaN         NaN
P018                NaN         NaN         NaN   NaN       0.00        1.20
P019               0.00        0.47         NaN  0.20        NaN         NaN
P020                NaN         NaN         NaN   NaN       0.00        0.84
P021               0.00         NaN        0.19  0.46        NaN         NaN
P022                NaN         NaN         NaN   NaN       0.00        2.65
P023               3.13         NaN         NaN  0.52        NaN         NaN
P024                NaN         NaN         NaN   NaN       0.00        1.61
P025               0.00        1.51        3.11  0.28        NaN         NaN
P026                NaN         NaN         NaN   NaN       0.00        1.95
P027               0.00        0.62         NaN  0.18        NaN         NaN
P028                NaN         NaN         NaN   NaN       0.00        1.43
P029                NaN        0.47        1.53  0.01        NaN         NaN
P030                NaN         NaN         NaN   NaN       0.00        1.36

image
primer-type
AOI         Rectangle 3  face
ID number
P001                NaN   NaN
P002               1.69  0.37
P003                NaN   NaN
P004               2.08  0.15
P005                NaN   NaN
P006               1.36  0.92
P007                NaN   NaN
P008               0.51  0.71
P009                NaN   NaN
P010               1.50  0.00
P011                NaN   NaN
P012               3.75  0.40
P013                NaN   NaN
P014               0.43  0.48
P015                NaN   NaN
P016               1.30  0.16
P017                NaN   NaN
P018               0.64  0.24
P019                NaN   NaN
P020               1.98  0.44
P021                NaN   NaN
P022               3.50  0.44
P023                NaN   NaN
P024               0.20  1.45
P025                NaN   NaN
P026               2.54  2.12
P027                NaN   NaN
P028                NaN  0.44
P029                NaN   NaN
P030               0.72  0.17

[30 rows x 62 columns]

In [129]:
for img in image_ratings_df.index:
    for primer_type in ('emotional', 'functional'):
        print(img, primer_type, " overall face rating: ",
              image_ratings_df[image_ratings_df.index == img]['image-face-rating-mean'].values[0])
        print(pivot_df[img][primer_type])
    break

1_kitchen emotional  overall face rating:  4.833333333333333
AOI        Not on AOI  Rectangle 2   face
ID number
P001              NaN          NaN    NaN
P002              NaN          NaN    NaN
P003              NaN         0.52   0.67
P004              NaN          NaN    NaN
P005              NaN          NaN   1.73
P006              NaN          NaN    NaN
P007             0.00         0.29   0.96
P008              NaN          NaN    NaN
P009             0.32         0.00   0.70
P010              NaN          NaN    NaN
P011             0.00         0.27   1.21
P012              NaN          NaN    NaN
P013             0.00         0.17   0.30
P014              NaN          NaN    NaN
P015             0.00       138.18   0.50
P016              NaN          NaN    NaN
P017              NaN          NaN  15.33
P018              NaN          NaN    NaN
P019             0.00         0.13   0.59
P020              NaN          NaN    NaN
P021             0.00         1.15   0.20
P022              NaN          NaN    NaN
P023             0.00          NaN   0.25
P024              NaN          NaN    NaN
P025             0.00         0.13   0.44
P026              NaN          NaN    NaN
P027             0.00         0.27   0.98
P028              NaN          NaN    NaN
P029             0.00         0.47   0.17
P030              NaN          NaN    NaN
1_kitchen functional  overall face rating:  4.833333333333333
AOI        Not on AOI  Rectangle 2  face
ID number
P001             0.00         1.18  0.18
P002             0.06         1.84  0.29
P003              NaN          NaN   NaN
P004             0.00         3.52  0.58
P005              NaN          NaN   NaN
P006             1.79         2.42  1.96
P007              NaN          NaN   NaN
P008              NaN          NaN   NaN
P009              NaN          NaN   NaN
P010             1.32         0.55  2.22
P011              NaN          NaN   NaN
P012             0.28         0.00  0.48
P013              NaN          NaN   NaN
P014             1.94         3.97  0.33
P015              NaN          NaN   NaN
P016             0.00         0.19  0.42
P017              NaN          NaN   NaN
P018             0.00         0.23  0.43
P019              NaN          NaN   NaN
P020             0.00         0.38  0.59
P021              NaN          NaN   NaN
P022             0.38         0.00  0.60
P023              NaN          NaN   NaN
P024             0.00          NaN  0.20
P025              NaN          NaN   NaN
P026              NaN          NaN   NaN
P027              NaN          NaN   NaN
P028             0.07         0.57  0.92
P029              NaN          NaN   NaN
P030             0.00         0.17  0.46